# https://dependabot.com/blog/introducing-config-files/
version: 1
update_configs:
  - package_manager: "ruby:bundler"
    directory: "sample_private_lib1"
    update_schedule: "daily"
    allowed_updates:
      - match:
          update_type: "all"

  - package_manager: "ruby:bundler"
    directory: "app"
    update_schedule: "daily"
    allowed_updates:
      - match:
          update_type: "all"
    ignored_updates:
      - match:
          dependency_name: "sample_private_lib1"
